---
title: "Bio 302 Exam 2018"
author: "Richard J. Telford"
date: "June 10, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Questions

1) Discuss the advantages and challenges of pre-registering an experiment. 

2) A statistical test has a p-value of 0.04.
 - How should this p-value be interpreted? Is it good evidence against the null hypothesis?

3) Explain what autocorrelation is, how it can be detected and how its effect on regression can be controlled for.

4) Model the relationship between total plant biomass in alpine grasslands and summer air temperature in China. Available data are biomass per species per plot. There are ~15 plots in each of four sites. Each site is at a different elevation and has a climate logger.  

Climate data can be downloaded from https://osf.io/34qnr/

Biomass data can be downloaded from https://osf.io/6sfqw/ (you already have these on Rstudio.cloud).

Calculate mean summer air temperatures each site. Use the logger "gradient". The OTC logger is part of another experiment. 

Calculate biomass per plot (you have already done this).

Join the climate data to the biomass data.

Choose and fit a suitable model to find the relation a biomass and mean summer temperature. 

Check the model's assumptions are met.

Report key statistics from your model in a table or in the text.

Make a publication quality plot that shows the relationship between biomass and mean summer temperature.

Write the statistical part of the methods and results sections of a manuscript describing the biomass-climate relationship. You should justify your choice of model.

Write a biological interpretation of your final model.					

Your manuscript should be fully reproducible. That is, I should be able to render your rmarkdown file and generate all results.
wd aee e 
## Instructions

Please answer all questions. Please do not google-copy-paste answers - I will check for plagiarism.  
 Your answers should be fully reproducible and include publication quality graphics where relevant. Submit as html or pdf and include the Rmarkdown file.

If there are problems, please ask me richard.telford@uib.no